### ISSUE TITLE
Module not found: Error: Can't resolve 'Quagga'

### ISSUE THREAD

**Issue by aflatoon2874** [neojato/ngx-barcode-input#1]
Hi neojato,

I have used your module in an Angular5 project as per your instructions. ng build/serve throws the following error:
"ERROR in ./node_modules/ngx-barcode-input/esm5/ngx-barcode-input.js
Module not found: Error: Can't resolve 'Quagga'"

quagga dependency is also installed. Can you please help resolve the issue.
Thanks

**Comment by neojato** [comment]
Hi @aflatoon2874,

Thanks for trying out this module. Are you using the most recent version (0.1.5)?

Cheers

**Comment by aflatoon2874** [comment]
Yes Kyle. I am using the latest version (0.1.5). The demo link on GitHub
also throws the same error.

Awaiting your response.

Thanks

**Comment by neojato** [comment]
I've tested the demo app on Chrome, FireFox, and Safari on OS X as well as on Android and iOS. I'm not able to reproduce this error.

Could you provide more details on how to reproduce your issue? Thanks in advance.

**Comment by aflatoon2874** [comment]
My environment is Fedora 28 x64, Node 8.11.1, angular 5.2.10, angular-cli
1.7.4, chrome 62.

**Comment by aflatoon2874** [comment]
Please find a new angular cli project with changes as per your instructions on GitHub. The app.component.html contains your html code. app.module.ts is updated to include your module. It does not compile when "ng serve/build" is run.

https://github.com/aflatoon2874/myapp

Kindly help.
Thanks

**Comment by neojato** [comment]
Thanks for providing an example. I've been traveling and will do my best to dig in and resolve asap.
